/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiErrorHandler: typeof import('./src/components/ApiErrorHandler.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    CreateItemView: typeof import('./src/components/CreateItemView.vue')['default']
    CurrencyInput: typeof import('./src/components/form/CurrencyInput.vue')['default']
    EditItemView: typeof import('./src/components/EditItemView.vue')['default']
    ListItemActions: typeof import('./src/components/ListItemActions.vue')['default']
    ListItemCard: typeof import('./src/components/ListItemCard.vue')['default']
    ListsOverview: typeof import('./src/components/ListsOverview.vue')['default']
    ListView: typeof import('./src/components/ListView.vue')['default']
    LoaderIndicator: typeof import('./src/components/LoaderIndicator.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    MessageComponent: typeof import('./src/components/MessageComponent.vue')['default']
    Messages: typeof import('./src/components/Messages.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    UserLists: typeof import('./src/components/UserLists.vue')['default']
  }
}
