/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ListItemActions: typeof import('./src/components/ListItemActions.vue')['default']
    ListItemCard: typeof import('./src/components/ListItemCard.vue')['default']
    ListsOverview: typeof import('./src/components/ListsOverview.vue')['default']
    ListView: typeof import('./src/components/ListView.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    UserLists: typeof import('./src/components/UserLists.vue')['default']
  }
}
