/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./src/components/AlertDialog.vue')['default']
    ApiErrorHandler: typeof import('./src/components/ApiErrorHandler.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    CreateItemView: typeof import('./src/components/ListComponents/CreateItemView.vue')['default']
    CreateListView: typeof import('./src/components/ListComponents/CreateListView.vue')['default']
    CurrencyInput: typeof import('./src/components/form/CurrencyInput.vue')['default']
    EditItemView: typeof import('./src/components/ListComponents/EditItemView.vue')['default']
    EditListView: typeof import('./src/components/ListComponents/EditListView.vue')['default']
    ListItemActions: typeof import('./src/components/ListComponents/ListItemActions.vue')['default']
    ListItemCard: typeof import('./src/components/ListComponents/ListItemCard.vue')['default']
    ListsOverview: typeof import('./src/components/ListComponents/ListsOverview.vue')['default']
    ListView: typeof import('./src/components/ListComponents/ListView.vue')['default']
    LoaderIndicator: typeof import('./src/components/LoaderIndicator.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    Messages: typeof import('./src/components/Messages.vue')['default']
    RenameListDialog: typeof import('./src/components/ListComponents/RenameListDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    UserLists: typeof import('./src/components/ListComponents/UserLists.vue')['default']
  }
}
